### ISSUE TITLE
Add Twitter cards in form and single candidat view and form

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#13]
Documentation: https://dev.twitter.com/cards/overview

We should adapt the type of card whether the candidat has a video or not.

This is a "nice to have", no rush.

**Comment by tielpi** [comment]
Hi ! 
An idea when this feature could be available ?
Now that we started sharing candidates messages on social networks, it would be very useful ! Thanks in advance !

**Comment by ColinMaudry** [comment]
Je n'avais pas trop de visibilité sur le besoin réel de cette feature, merci @tielpi de la confirmer.

Maintenant qu'on a une meilleure maîtrise de l'ajout de métadonnées sociales, ça devrait être facile.

**Comment by ColinMaudry** [comment]
@tielpi Pourrait-tu décrire le résultat souhaité dans Twitter ?

- Image
- Texte

**Comment by tielpi** [comment]
C'est assez bien décrit ici : http://fr.oncrawl.com/2016/un-guide-complet-pour-les-twitter-cards/
L'exemple de Techcrunch présenté sur cet page me semble le plus correspondre à ce que nous voulons et sinon, regarder sur la page Facebook MAVOIX les miniatures des candidatures que l'on a partagées, l'idée c'est d'avoir quelque chose d'approchant pour Twitter et Instagram si possible (du coup, j'ouvre une autre issue spécifique Instagram)

**Comment by tielpi** [comment]
@ColinMaudry @oceanBigOne 
Une chance que cette feature puis être dispo demain ?
On voudrait pouvoir partager les candidatures plus largement (une par une) sur Twitter et sasn la Twitter card, c'est vraiment bcp moins facile ;-)
Désolé d'insister !

**Comment by oceanBigOne** [comment]
je regarde et je reviens vers vous rapidement.

@ColinMaudry, quoi qu'il arrive, je ne pense pas que ce remette en cause ta phase de test (ce n'est pas une modification critique).

**Comment by oceanBigOne** [comment]
Bon a priori pas compliqué (c'est fait, mais je peux pas tester le partage twitter avec mon hébergement en local).  
@ColinMaudry si tu peux aussi tester ça en ligne quand tu peux :s... merci :s

@tielpi si tout ce passe bien ca sera en place avec la prochaine mise à jour

**Comment by tielpi** [comment]
Cool ! Vous êtes trop forts ! Et elle est quand la prochaine mise à jour ?

**Comment by oceanBigOne** [comment]
Je pense que si la phase de test se passe bien ça peut-être bon demain ... si ça se passe mal ... un peu plus :p 
@ColinMaudry je suis dispo pour le merge ce soir et/ou demain, hésites pas à m'envoyer un SMS pour que je sois plus réactif.

**Comment by ColinMaudry** [comment]
@oceanBigOne Sur la page d'un candidat, plusieurs métadonnées ont des adresses en HTTP :

- og:image
- twitter:image

A chaque fois c'est l'URL de l'image. Et ça peut causer des soucis. D'ailleurs le debugger de Twitter n'affiche pas l'image.

**Comment by tielpi** [comment]
Vous êtes à fond ce soir les gars ;-) Merci merci merci pour tout ce que vous faites !

**Comment by oceanBigOne** [comment]
Normalement, c'est l'url du fichier de config qui est utilisée, donc ca devrait fonctionner (pas de https chez moi pour tester)

**Comment by ColinMaudry** [comment]
Voilà, on est bon pour la page candidat. Manque plus qu'à faire de même pour la page du formulaire (et rajouter les balises OpenGraph aussi... #32)

**Comment by ColinMaudry** [comment]
Done.
