### ISSUE TITLE
Unlock subscription for people who live abroad

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#17]
To become député, a person simply need to have all the rights of an électeur, which includes people with French nationality who live abroad.

- phone number:
  - either you add a drop down with international phone prefixes, defaulting on +33
  - or you make it an open field, with only numbers, +, spaces, dots allowed to validate the form. Spaces and dots can (should) be removed before being recorded in the DB.
- address: dropdown of country names, in French, defaulting to France

**Comment by oceanBigOne** [comment]
Are you sure ? When i ask ato add country in adresse form, you say me no.

If yes, I need to add country in adress form too. ok ?

**Comment by ColinMaudry** [comment]
Yes, but I forgotten French expats can vote, thus can be candidats.

Yes, please add a dropdown menu of country names, in French, defaulting to France.
