### ISSUE TITLE
Enable submission of Extrait casier judiciaire and copy of ID

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#2]
Remove submission of Attestation d'inscriptions aux listes électorales.

**Comment by oceanBigOne** [comment]
Ok, i'm going to add 2 new uploads input file and remove "Attestation".  Are this new fields mandatory to submit form ?

**Comment by ColinMaudry** [comment]
No, same story as the attestation : we give the user the opportunity to upload it at once, but they can do it.

**Comment by oceanBigOne** [comment]
ok ! :)

**Comment by ColinMaudry** [comment]
Labels of the new documents:

- Extrait de casier judiciaire B3. Ce document peut être téléchargé sur [ce site Web](https://www.cjn.justice.gouv.fr/cjn/b3/eje20).
- Copie de votre carte d'identité recto/verso ou de votre passeport

**Comment by oceanBigOne** [comment]
Done :)
