### ISSUE TITLE
Remove all references to Attestation d'inscription sur les listes électorales

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#20]
We figured out that the process to get this document is very long and vary a lot from a city to another.

We consequently fully switched to copy of ID + extrait casier judiciaire.

Pages impacted:

- candidature form
- admin list
- admin singe candidat

**Comment by oceanBigOne** [comment]
Are you sure ? I think this is a feature for the admin later ? no ?

**Comment by ColinMaudry** [comment]
There are still some in Admin.
