### ISSUE TITLE
Enable upload of extrait casier judiciaire on March 12th

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#27]
Nous sommes maintenant le 14 mars, il est temps d'implémenter l'upload du casier judiciaire.

Texte :
> L'extrait de casier judiciaire B3 est le document qui indique si certains délits ou crimes ont été commis par la ou le candidat. Il est nécessaire pour se présenter aux élections législatives. Vous pouvez demander à ce qu'il vous soit envoyé par courrier à cette adresse. Ce document n'est pas nécessaire pour valider le formulaire, mais vous devrez nous l'envoyer avant le 25 avril. L'email de confirmation de candidature contient un lien pour modifier votre candidature et envoyer une copie numérisée de ce document.

**Comment by ColinMaudry** [comment]
@oceanBigOne La priorité niveau développement, c'est ça :)

**Comment by ColinMaudry** [comment]
Texte à ajouter au mail de confirmation et au texte de confirmation *si le candidat n'a pas envoyé d'extrait de casier judiciaire.*

> Votre candidature est bien enregistrée, mais vous ne serez admissible au tirage au sort que lorsque vous nous aurez envoyé un extrait de casier judiciaire B3 valide.

**Comment by ColinMaudry** [comment]
@oceanBigOne Tu prends l'ajout du champs dans le formulaire et l'ajout du bouton de validation du document dans la page /admin/candidature/fiche.

Je m'occupe du texte.

On fera le ménage dans #8 dans la release 1.5.0.

**Comment by oceanBigOne** [comment]
Done.

J'ai ajouté une variable disponible dans le twig du mail (text et html) isCriminalRecordSent pour que tu puisses mettre le texte que si il n'y a pas le fichier.

`{% if isCriminalRecordSent==false %} ton texte {% endif %}`

**Comment by ColinMaudry** [comment]
OK. Et j'imagine que cette variable n'est pas dispo sur la page du mail de confirmation :) Tant pis, je ferais un "Si...".

**Comment by oceanBigOne** [comment]
je viens d'ajouter l'objet sur la page de success. j'utilise une variable de session pour éviter qu'un utilisateur puisse se servir de cette page pour se balader sur les autres candidature. (pas problématique aujourd'hui mais si on commence à afficher plus d'info ca pourrait être problématique). Seule limite de l'utilisation de la session. Si l'utilisateur actualise sa page après 3 min, l'objet ne sera plus accessible.

J'ai mis des exemple d'utilisation de l'objet dans le twig success (en commentaire twig) `{# #}`

**Comment by ColinMaudry** [comment]
Je finis le rédactionnel demain pour expliquer :

- pourquoi on a besoin de ce document
- qu'il n'est pas nécessaire de l'envoyer pour valider le formulaire
- qu'il faut l'envoyer avant le 25 avril pour valider la candidature
- comment l'envoyer une fois le formulaire validé

(ça fait beaucoup de choses)
