### ISSUE TITLE
Mettre en place une routine de sauvegarde de la base de données et des documents

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#28]
De façon à prévenir une perte des données, nous devons mettre en place des sauvegardes automatisées et sécurisées.

Cette sauvegarde :

- sera quotidienne
- contiendra
  - un dump SQL de la base de données
  - les copies des documents d'identité
  - les photos
- sera sécurisée (SSH/SFTP)
- sera stockée sur un autre serveur

**Comment by ColinMaudry** [comment]
(@oceanBigone compte tenu du contexte de ce projet, je pense que le français est préférable pour les issues)

**Comment by ColinMaudry** [comment]
Le script est rédigé, mais ne fonctionne pas avec cron.

Le soucis est qu'avec un cron job, il n'y a aucune variable d'environnement : pas de PATH, pas de HOME, rien.

Mon script faisant appel à la configuration SSH et à la clé de l'utilisateur, le script échoue car il ne les trouve pas.

Donc soit je (on) trouve un moyen de déclarer les variables qui permettent au script de s’exécuter dans un contexte cron.

Soit on trouve un autre moyen de planifier une sauvegarde quotidienne dans un environnement Linux.

Pour l'instant, je le fais à la main, et ça marche, donc c'est pas critique.

**Comment by daviddelon** [comment]
Tu peux passer la clef utilisateur  avec l'option -i de ssh. Par exemple : ssh  -i /var/backups/.ssh/id_rsa'  . 
C'est jouable également avec rsync (c'est de cette façon que je l'utilise) : 
rsync  -e 'ssh  -i /var/backups/.ssh/id_rsa'  source destination

**Comment by ColinMaudry** [comment]
Le flux des candidatures s'est beaucoup ralenti, du coup les backups manuels semblent suffire pour l'instant.
