### ISSUE TITLE
Ajouter un champs "Commentaires" dans l'admin

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#29]
Afin de garder une trace du statut de la validation du candidat, notamment les échanges avec elle ou lui.

**Comment by ColinMaudry** [comment]
La colonne devrait s'appeller `comment`, je l'ai appellée comme ça dans list.html.twig.

**Comment by ColinMaudry** [comment]
Dans list.html.twig, j'avais donc créé un espace pour afficher ce commentaire. Le CSS est prêt, il y a juste à vérifier que le commentaire s'affiche bien :

```
<div class="scrollable">
                    {{ candidature.comment }}
</div>
```

**Comment by oceanBigOne** [comment]
done.
J'en ai profité pour changer l'entete du formulaire quand on est admin (j'ai enlevé les case à cocher d'engagement pour mettre le bloc de texte). Je ferme pas l'issue si tu veux passer dessus graphiquement ?

**Comment by ColinMaudry** [comment]
Ce serait bien que les retours à la ligne du commentaire persistent. Pour le texte de témoignage, ils persistent.

Je release tel quel pour l'instant mais je laisse ouvert en baissant la priorité :)

**Comment by oceanBigOne** [comment]
J'ai pas le problème chez moi. Tu peux mettre à jour le serveur de dev quand tu as le temps que je puisse visualiser/tester le souci ?

**Comment by ColinMaudry** [comment]
C'est bon, c'était dans la vue liste.
