### ISSUE TITLE
Normaliser la casse des noms de famille (mise en majuscules)

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#30]
Afin d'améliorer la lisibilité des candidatures, il serait utile de normaliser la casse des noms de famille.

En France, la tradition veut que comme de nombreuses personnes ont un nom de famille qui est aussi un prénom, le nom de famille soit en majuscules.

Je trouve ça moche, mais je pense que c'est la marche à suivre.

**Comment by ColinMaudry** [comment]
Les noms de famille doivent être mis en majuscules avant d'être entrés en base de données, de façon à normaliser leur affichage par la suite (validation, organisation du tirage au sort).

**Comment by oceanBigOne** [comment]
DONE
