### ISSUE TITLE
Ajout de métadonnées OpenGraph (Facebook)

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#32]
Pour qu'une image et un texte de description s'affichent quand on partage la page.

**Comment by ColinMaudry** [comment]
- Les métadonnées OG doivent être appelées par le bon bloc pour ne pas être dupliquées
- og:url doit toujours être présent et contenir l'URL de la page courante

**Comment by ColinMaudry** [comment]
Les métadonnées OG que j'ai mises dans base.html.twig sont destinées à la page candidatures.html.twig. Du coup, pour l'instant, il y a juste pour form.html.twig qu'on a pas encore vraiment de métadonnées OG dédiées.

**Comment by oceanBigOne** [comment]
done
