### ISSUE TITLE
En plus du bouton "Enregistrer", ajouter un bouton "Enregistrer et mettre en ligne" pour l'admin

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#38]
Actuellement, les validateurs doivent revenir à la page du candidat pour le mettre en ligne, après l'avoir édité. C'est très fastidieux.

Nous devrions donc ajouter un bouton "Enregistrer et mettre en ligne" en dessous de "Enregistrer", qui n'apparaîtrait que si c'est un admin qui affiche la page. Pas le candidat !

Lorsqu'on clique sur "Enregistrer et mettre en ligne" :

1. Le contenu du formulaire est sauvegardé
2. Le candidat édité est mis en ligne
3. Le validateur est redirigé vers la listes des candidatures (/candidature/list.html)

**Comment by oceanBigOne** [comment]
Concernant la redirection sur la liste des validations, si on est OK je le fait sur les deux boutons (le submit normal et submit avec validation). Par contre, il faut que je rajoute une sauvegarde et un rechargement des options d'affichage sinon l'utilisateur va se rendre fou pour savoir ou il en est à chaque retour. 

Ok pour ca ?

**Comment by oceanBigOne** [comment]
Done
