### ISSUE TITLE
Capitaliser la première lettre des noms de ville en entrée et en sortie

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#39]
On peut supposer que tout nom de ville commence pas une majuscule. Malheureusement, beaucoup de candidats écrivent le nom de leur ville en minuscules.

Afin d'y remédier, il faudrait capitaliser la première lettre du nom de la ville :

- en entrée de base, lorsqu'un candidat enregistre sa candidature
- en sortie de base, lorsqu'un nom de ville est affiché (pour les noms de ville déjà en base)

**Comment by oceanBigOne** [comment]
DONE

**Comment by ColinMaudry** [comment]
Attention, je pense que `ucwords` est différent de `capitalize`. "upper case words" met en majuscule la première lettre de chaque mot, tandis que `capitalize` ne semble mettre en majuscule que la première lettre de la chaîne de caractères.

Et c'est un comportement comme `ucwords` qu'il nous faut. Ou alors, au pire, une stricte mise en majuscule de la première lettre de la chaîne de caractères, sans toucher aux autres lettres. C'est ce à quoi je pensais à l'origine.

Ça vaut aussi pour les prénoms > #42

**Comment by oceanBigOne** [comment]
C'est noté, je m'en occupe en même temps que #42 

Pour moi, il faut passer toutes les lettre en minuscule, sauf la première de chaque mot. ex : "Jean Paul" ou "Aix En Provence"

**Comment by ColinMaudry** [comment]
Hmmm attend je crois qu'on peut faire mieux.

**Comment by ColinMaudry** [comment]
Il y a trop de noms de villes composés pour utiliser `ucwords`.

`capitalize` ne convient pas non plus, car il met en minuscule toutes les autres lettres.

Solution : ne capitaliser que la première lettre, au moyen d'un `split`, et ne pas toucher aux autres.

S'il y a des modifications à faire sur les autres lettres le validateur s'en chargera.

**Comment by oceanBigOne** [comment]
Done (à tester sur dev avec un accent en première lettre, toujours pour mon doute concernant les différences d'encodage windows/linux)
