### ISSUE TITLE
Edition et validation ID

### ISSUE THREAD

**Issue by tielpi** [MaVoix/candidature#40]
Merci beaucoup pour l'ajout de la zone commentaire et le bouton "enregistrer et mettre en ligne" ! (je suppose que seuls les admin ont accès à ce bouton, pas les candidats ?) 
Ça simplifie beaucoup le process et les commentaires vont nous permettre de partager vraiment la validation dans la team.
Un point d'amélioration supplémentaire serait de pouvoir valider l'ID dans le tableau ou au moment de l'édition.
Le process est le suivant, quand une candidature arrive : 
1-check ID
2- ID OK ou non (si non commentaire dans édition)
3 - édition
4 - mise en ligne
À ce stade, pour valider l'ID, il faut cliquer sur la photo, aller dans la fiche, cliquer sur "on" puis sur éditer... si on pouvait le faire dans la colonne action du tableau ou en éditant (comme la mise en ligne) on gagnerait encore en fluidité ;-)

**Comment by ColinMaudry** [comment]
En fait la vue fiche n'est pas utile, c'est juste qu'elle a tous les boutons :)

On pourrait déplacer les boutons vers la vue tableau et remplacer la vue fiche par la vue édition.

**Comment by ColinMaudry** [comment]
@oceanBigOne Tu as avancé là-dessus ? C'est à tester ?

**Comment by oceanBigOne** [comment]
Ben j'ai l'impression que c'est bon. (ID accessible depuis le tableau), mais je n'ai pas forcément tout compris sur ce dossier.

**Comment by ColinMaudry** [comment]
Je pense qu'on devrait ajouter le bouton de validation de l'ID (et donc aussi de l'extrait de casier #27) dans la colonne Action de la vue "liste".

Comme ça on peut visualiser les documents et les valider dans la même vue.
