### ISSUE TITLE
Prénom composés / min / maj

### ISSUE THREAD

**Issue by tielpi** [MaVoix/candidature#42]
Quand les candidat.e.s ont des prénoms composés, le deuxième prénom est mis en minuscule et il est impossible de le corriger

**Comment by ColinMaudry** [comment]
Mmmh je pense que @oceanBigOne force la mise en minuscule des autres lettres, alors qu'il faut juste forcer la mise en majuscule de la première.

**Comment by oceanBigOne** [comment]
Effectivement ! .. je suis sur un hotfix à ce sujet là au niveau de l'export (démarrer entre midi et deux, je reprend ce soir). 

J'en profite pour uniformiser tout ça. Mais pour moi, il faut passer la première lettre de chaque mot en majuscule : "Jean Paul", "Aix En Provence" etc...  
(il y a une différence de comportement dans les fonctions que j'utilise que je n'avais pas remarqué, désolé pour ça)

**Comment by ColinMaudry** [comment]
Pour les prénoms OK de capitaliser chaque mot :+1:

**Comment by oceanBigOne** [comment]
Je viens de faire la modification pour les prénoms uniquement. A tester sur le serveur de dev avant (j'ai un doute sur la gestion de l'encodage). Il faut tester un un prénom commençant par un caractère accentué. genre "Élise"

**Comment by ColinMaudry** [comment]
Il semblerait que seule la première lettre de toute la chaîne soit mise en majuscule sur la page candidat, et les autres en minuscule.
https://github.com/MaVoix/candidature/blob/develop/templates/visitor/candidature/candidat.html.twig#L52

On veut la première lettre de chaque mot.

**Comment by oceanBigOne** [comment]
Effectivement, un oubli sur cette page.

**Comment by ColinMaudry** [comment]
Mais il y a aussi une correction en entrée de base, ou juste à l'affichage ? Idéalement faudrait que le contenu en base soit nickel pour les nouvelles candidatures.

**Comment by oceanBigOne** [comment]
Pas trop d'avis sur la question ... je suis revenu en arrière sur ce point en me disant que c'était pas plus mal de conserver la saisie utilisateur "brut". Mais franchement je fais comme tu me dis (pour moi les deux visions se défendent et ça ne me pose aucun problème).

**Comment by ColinMaudry** [comment]
OK, on garde tel quel en entrée.
