### ISSUE TITLE
Verso ID 

### ISSUE THREAD

**Issue by tielpi** [MaVoix/candidature#43]
Un des pb majeurs que l'on rencontre sur les ID, ce sont les gens qui ne mettent que le recto. Prévoir un petit message en dessous du champ disant : "si vous n'arrivez pas à joindre le recto et le verso de votre carte d'identité, merci d'envoyer le verso à : mavoixjuin2017@mavoix.info" ?

**Comment by ColinMaudry** [comment]
Ou alors

> Si vous n'avez pas réussi à mettre le recto et le verso dans un même fichier, voici un deuxième champ pour envoyer l'autre face

**Comment by oceanBigOne** [comment]
oui, personnellement je pense aussi que le deuxième champs est une solution plus propre (surtout pour vous faciliter l'administration en conservant toutes les pièces au même endroit). Je m'en occupe dès que possible.

**Comment by ColinMaudry** [comment]
C'est pas courant comme pratique, donc il faudra veiller à ce qu'ils ne nous envoient pas deux documents différents, ou deux fois le même :D.

**Comment by oceanBigOne** [comment]
A tester sur dev. Si ok, on peut fermer l'issue
