### ISSUE TITLE
Faire apparaître les menus "Formulaire, Candidats, Connexion" sur la version mobile

### ISSUE THREAD

**Issue by tielpi** [MaVoix/candidature#44]
Le menu jaune en haut de la page candidature.mavoix.info ne fait rien apparaître à droite dans la version mobile. c'est surtout problématique pour les gens qui veulent accéder à la liste des candidats à partir de cette adresse (après, si on ne peut pas se connecter sur mobile, c'est la vie !)

**Comment by ColinMaudry** [comment]
Pas d'accord pour Connexion : l'interface admin n'est pas prévue pour marcher sur mobile.

OK pour les pages publiques.

**Comment by tielpi** [comment]
Ça me va ! Je me suis mal exprimé, l'idée était simplement que les gens puissent accéder facilement à la galerie des candidats ;-)

**Comment by ColinMaudry** [comment]
Si tout les tests pour la 1.4.0 roulent tout seul, j'implémente ça dans la même release. Sinon, ce sera pour la prochaine.

**Comment by oceanBigOne** [comment]
J'ai mis à jour le menu sur une feature à part, on pourra merge dans la version que vous voulez. 

J'ai quand même mis à jour l'admin ... au pire c’est juste inutile, au mieux ça sera ça de fait si on bascule l'admin en responsive)
