### ISSUE TITLE
Bug export CVS

### ISSUE THREAD

**Issue by tielpi** [MaVoix/candidature#46]
Quand on exporte la liste en CVS, la colonne candidature en ligne affiche NON partout, ce qui d'une part est faux et d'autre part empêche de faire un tri oui/,non qui nous est nécessaire pour avoir la bonne liste de mail lors d'un envoi comme hier soir (j'ai fait à la main, ça va encore, car il y en a une grosse centaine, mais ça va être de moins en moins facile)

**Comment by oceanBigOne** [comment]
Effectivement :/ ... jolie faute de frappe de mon côté. désolé pour ça. (bug corrigé sur la branche dévelop)
