### ISSUE TITLE
Cliquer sur Editer met la candidature hors ligne

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#47]
Aujourd'hui, l'écran d'édition est inaccessible si la candidature est en ligne.

Du coup, s'il veut éditer, le validateur met hors ligne puis édite.

L'idée serait que cliquer sur le bouton met automatiquement la candidature hors ligne.

**Comment by oceanBigOne** [comment]
Dangereux non ? (si l'admin clique par erreur et reviens en arrière, la candidature aura basculé offline)

**Comment by ColinMaudry** [comment]
Moui, peut-être. Qu'en pense @tielpi ?

**Comment by tielpi** [comment]
D'accord avec toi @ColinMaudry

**Comment by ColinMaudry** [comment]
Donc... go ! (enfin d'abord on livre la 1.4.0 :D)
https://github.com/MaVoix/candidature/milestone/7

**Comment by oceanBigOne** [comment]
oui, c'est noté :)

**Comment by oceanBigOne** [comment]
Avec les modifs de l'issue #49, cette demande n'a plus lieu d'être on est ok ?
(Les admins peuvent maintenant éditer les candidatures online)

**Comment by oceanBigOne** [comment]
ah ben non :/ j'ai pas fait ca... (l'edition en admin ne change pas l'état). je corrige !

**Comment by ColinMaudry** [comment]
Pour clarifier : effectivement, le bouton Editer n'a plus d'effet sur la mise en ligne/hors ligne, c'est la sauvegarde de la candidature qui le permet.
