### ISSUE TITLE
Sur la page publique des candidatures, impossible d'ouvrir une candidature dans un nouvel onglet

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#48]
L'ouverture d'une candidature se fait de façon un peu spéciale (javascript ?), ce qui fait qu'on ne peut pas ouvrir une candidature dans un nouvel onglet, ou sauvegarder le lien vers la candidature ("Copier l'adresse du lien").

C'est pas grave, mais c'est déroutant.

Est-il possible de faire un lien normal ? Quels sont les avantages de l'approche actuelle ?

**Comment by oceanBigOne** [comment]
Ben non, aucune raison :/ ...(et donc aucun avantage !) Je viens de corriger. Je pense que j'ai du tester des affichages vignettes plus complexes au début, ça devait avoir un intérêt à ce moment là... mais là, je vois vraiment pas)
