### ISSUE TITLE
Améliorer l'ergonomie de la validation

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#50]
Les petits chamboulements de la version 1.4.0 ont accouché d'une ergonomie très moyenne pour les validateurs. L'objectif est donc de trouver les mesures qui permettraient de rétablir une ergonomie sensée, sans demander trop de développements.

La vue de prévisualisation doit être conservée.

Retour utilisateur :

> je dois ouvrir la fiche en read only, valider la CNI, puis revenir sur la liste, pour pouvoir éditer la fiche, faire les corrections nécessaires puis enregistrer

**Comment by ColinMaudry** [comment]
Propositions :

- permettre la mise en ligne et la validation des documents
  - sur la vue liste
  - sur la vue de prévisualisation
- donner accès à l'édition de la candidature depuis la prévisualisation
- ajouter un bouton "prévisualiser" dans la vue liste (en plus du clic sur la photo)
-  en vue édition, lorsqu'on enregistre la fiche, rediriger vers la vue liste, centrée sur la candidature que l'on vient d'enregistrer

**Comment by sulian0** [comment]
Parfait :+1: 
Si vous n'avez pas beaucoup de temps et que vous voulez limiter les devs, ces 2 points me semblent les plus importants : 
- ajouter un bouton "éditer" dans la prévisualisation
- ajouter des liens vers la carte ID et l'extrait de casier judiciaire dans la prévisualisation
