### ISSUE TITLE
Ajouter une page n'affichant que les candidats tirés au sort

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#55]
Maintenant que les candidats sont tirés au sort, nous avons besoin d'une page dédiée n'affichant que ces candidats.

Cette feature a donc deux volets :

- l'ajout dans la table `candidature` d'une colonne 'tire_au_sort' (booléen)
- la création d'une page analogue à /candidature/candidatures.html, mais n'affichant que les candidats tirés au sort

@olivM, tu pourrais t'en charger ? Je suis dispo cet aprem pour en discuter et m'assurer que tu arrives à déployer l'appli en local.

**Comment by olivM** [comment]
ok je regarde ça en fin d'après-midi

**Comment by ColinMaudry** [comment]
Comme c'est du one shot, pas besoin de switch on/off dans l'interface : j'enverrai un CSV à @tielpi qu'il éditera et nous renverra pour import dans la base.

**Comment by tielpi** [comment]
ça me va !

**Comment by tielpi** [comment]
Merci d'avance ;-)

**Comment by olivM** [comment]
Hello,

Je viens de publier la feature.

Je pense qu'il faudrait ajouter :
 - le statut candidat ou suppléant
 - la circonscription


et du coup mettre tout cela sur une carte ( je vois qu'il y en a déjà une répertoriant tous les candidats au tirage au sort )
