### ISSUE TITLE
Format admin single candidature view

### ISSUE THREAD

**Issue by ColinMaudry** [MaVoix/candidature#8]

**Comment by ColinMaudry** [comment]
Cette vue n'est utilisée que pour les boutons de validation. Pour visualiser le contenu, les validateurs utilisent la vue d'édition.

Du coup, cette vue est amenée à disparaître.

**Comment by oceanBigOne** [comment]
Je suis d'accord sur ce point, il faudrait cependant permettre à l'admin d'afficher la page candidat même quand elle est offline pour qu'il puisse avoir un aperçu. (je m'en occupe des que possible)

**Comment by ColinMaudry** [comment]
La vue édition, il a un aperçu non ?

Et si elle est en ligne, cliquer sur "Editer" la mettrait automatiquement hors-ligne.

**Comment by oceanBigOne** [comment]
Pas sûr de comprendre. Je viens de faire une modif là. Tu me diras.

**Comment by oceanBigOne** [comment]
ok, je viens de comprendre un problème, je sais pas si c'est celui là dont tu parles :( ya plus les boutons de validations des documents du coup.

**Comment by oceanBigOne** [comment]
Je viens de les remettre

**Comment by ColinMaudry** [comment]
L'idée était de n'avoir que deux vues pour l'admin : 

- le tableau de liste des candidats
- le mode édition
- supprimer /admin/candidature/fiche

Les boutons seraient donc sur les deux vues restantes.
